// components/exerciseLibrary.js
// Bibliothèque d'exercices statique en français — pas de dépendance externe.
// Organisée par groupe musculaire pour le drawer.

export const GROUPS = [
  { value: 'Tous', label: 'Tous' },
  { value: 'Pectoraux', label: 'Pectoraux' },
  { value: 'Dos', label: 'Dos' },
  { value: 'Jambes', label: 'Jambes' },
  { value: 'Épaules', label: 'Épaules' },
  { value: 'Bras', label: 'Bras' },
  { value: 'Abdos', label: 'Abdos' },
]

export const GROUP_COLORS = {
  Pectoraux: '#E63946',
  Dos: '#3A86FF',
  Jambes: '#FF9F1C',
  Épaules: '#8338EC',
  Bras: '#06D6A0',
  Abdos: '#FFB703',
  Autre: '#7A7A7A',
}

export const EXERCISE_LIBRARY = {
  Pectoraux: [
    'Développé couché barre',
    'Développé couché haltères',
    'Développé couché prise serrée',
    'Développé incliné barre',
    'Développé incliné haltères',
    'Développé décliné barre',
    'Développé décliné haltères',
    'Développé couché tempo',
    'Développé couché pause',
    'Développé couché box (planche sur poitrine)',
    'Développé couché Larsen (sans jambes)',
    'Développé couché Spoto (pause au-dessus poitrine)',
    'Développé couché pieds surélevés (feet up)',
    'Développé couché chaînes',
    'Développé couché bandes élastiques',
    'Développé couché prise large',
    'Développé couché barre safety squat',
    'Écarté haltères (plat)',
    'Écarté incliné haltères',
    'Écarté couché câble (pec deck)',
    'Pec deck machine',
    'Dips (poids de corps)',
    'Dips lestés',
    'Pompes',
    'Développé Smith machine',
    'Cable crossover',
  ],
  Dos: [
    'Soulevé de terre barre',
    'Soulevé de terre sumo',
    'Soulevé de terre roumain (RDL)',
    'Soulevé de terre jambes tendues',
    'Soulevé de terre déficit',
    'Soulevé de terre block pulls (surélevé)',
    'Soulevé de terre pause',
    'Soulevé de terre tempo',
    'Soulevé de terre chaînes',
    'Soulevé de terre bandes élastiques',
    'Soulevé de terre prise mixte',
    'Soulevé de terre snatch grip',
    'Rowing barre (pronation)',
    'Rowing barre (supination)',
    'Rowing haltère unilatéral',
    'Rowing T-bar',
    'Rowing buste penché câble',
    'Tractions (poids de corps)',
    'Tractions lestées',
    'Tractions pronation large',
    'Tractions supination (chin-up)',
    'Tirage poulie haute (lat pulldown)',
    'Tirage horizontal câble',
    'Tirage poitrine prise serrée',
    'Face pull câble',
    'Hyperextensions lombaires',
    'Good Morning barre',
  ],
  Jambes: [
    'Squat barre (back squat)',
    'Squat avant (front squat)',
    'Squat bulgare (split squat)',
    'Squat sumo',
    'Squat gobelet (goblet squat)',
    'Squat tempo',
    'Squat pause',
    'Squat box (box squat)',
    'Squat pin (pin squat)',
    'Squat bandes élastiques',
    'Squat chaînes',
    'Squat safety bar (SSB)',
    'Squat ceinture (belt squat)',
    'Squat déficit',
    'Leg press',
    'Hack squat',
    'Fentes marchées haltères',
    'Fentes bulgares',
    'Romanian Deadlift (RDL)',
    'Leg curl couché machine',
    'Leg curl assis machine',
    'Leg extension machine',
    'Hip thrust barre',
    'Soulevé de terre jambes tendues',
    'Mollets debout machine',
    'Mollets assis machine',
    'Presse à cuisses inclinée',
    'Adducteurs machine',
    'Abducteurs machine',
  ],
  Épaules: [
    'Développé militaire barre',
    'Développé militaire haltères',
    'Développé Arnold',
    'Push press',
    'Développé Smith machine épaules',
    'Élévations latérales haltères',
    'Élévations latérales câble',
    'Élévations antérieures haltères',
    'Oiseau haltères (rear delt)',
    'Oiseau machine (peck deck inversé)',
    'Tirage menton barre',
    'Shrugs barre (trapèzes)',
    'Shrugs haltères',
    'Face pull câble',
    'Arnold press',
  ],
  Bras: [
    'Curl biceps barre droite',
    'Curl biceps barre EZ',
    'Curl haltères alterné',
    'Curl marteau haltères',
    'Curl incliné haltères',
    'Curl câble basse poulie',
    'Curl pupitre (Scott)',
    'Curl barre au pupitre',
    'Skull Crusher barre',
    'Extensions triceps barre EZ',
    'Pushdown câble (corde)',
    'Pushdown câble (barre)',
    'Extensions triceps haltère (au-dessus tête)',
    'Dips banc triceps',
    'Kickback triceps haltère',
    'Curl concentré haltère',
  ],
  Abdos: [
    'Crunch',
    'Crunch câble',
    'Planche (Plank)',
    'Relevé de jambes suspendu',
    'Relevé de jambes au sol',
    'Ab wheel',
    'Russian twist',
    'Side plank',
    'Crunch machine',
    'Mountain climbers',
    'Gainage dynamique (dead bug)',
  ],
}

// Liste plate pour la recherche texte (avec groupe attaché)
export function getFlatList() {
  const flat = []
  for (const [group, names] of Object.entries(EXERCISE_LIBRARY)) {
    names.forEach(name => flat.push({ name, group }))
  }
  return flat
}
